name: Test
on: push # when code changes are pushed to remote origin
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Node.js
        - uses: actions/setup-node@v3
          with:
            node-version: 16
      - name: Install dependencies
        run: npm ci # similar to npm install
      - name: Run unit test
        run: npm test